// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/api/api.ts";
import * as $1 from "./routes/consultation.tsx";
import * as $2 from "./routes/contacts.tsx";
import * as $3 from "./routes/index.tsx";
import * as $4 from "./routes/lawyers.tsx";
import * as $5 from "./routes/lawyers/[name].tsx";
import * as $$0 from "./islands/NavbarMobile.tsx";
import * as $$1 from "./islands/gallery.tsx";
import * as $$2 from "./islands/lawyer.tsx";
import * as $$3 from "./islands/myFooter.tsx";

const manifest = {
  routes: {
    "./routes/api/api.ts": $0,
    "./routes/consultation.tsx": $1,
    "./routes/contacts.tsx": $2,
    "./routes/index.tsx": $3,
    "./routes/lawyers.tsx": $4,
    "./routes/lawyers/[name].tsx": $5,
  },
  islands: {
    "./islands/NavbarMobile.tsx": $$0,
    "./islands/gallery.tsx": $$1,
    "./islands/lawyer.tsx": $$2,
    "./islands/myFooter.tsx": $$3,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
